version: '2.1'

services:
  # App
  common-app:
    build: ./
    #env_file: .env.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/api-graphql/src
    ports:
      - "3000:3000"
    command: yarn dev 

  realworld-graphql:
    extends: common-app

  realworld-graphql-prod:
    extends: common-app
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: yarn start

